# Generated by Django 3.2.4 on 2021-06-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210617_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=4)),
                ('rego', models.CharField(max_length=6)),
                ('customers', models.ManyToManyField(to='customers.Customer')),
            ],
        ),
    ]
