# Generated by Django 3.2.4 on 2021-06-17 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='customers',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
